import pyautogui as pg
import time
pg.click(76,973)
time.sleep(2)
pg.click(1565,178)
time.sleep(2)
pg.click(1547,792)
time.sleep(2)
pg.typewrite(["enter"])
time.sleep(2)
pg.typewrite("ifconfig")

pg.typewrite(["enter"])
time.sleep(2)
pg.typewrite("ls")

pg.typewrite(["enter"])
time.sleep(2)
pg.typewrite("mkdir harshan")
pg.typewrite(["enter"])
time.sleep(2)
pg.typewrite("ls")
pg.typewrite(["enter"])
# pg.typewrite("exit")
# pg.typewrite(["enter"])